### ISSUE TITLE
Invoke-AsBuiltReport.Veeam.VBR.ps1 not found

### ISSUE THREAD

**Issue by salmeida77** [AsBuiltReport/AsBuiltReport.Veeam.VBR#1]
Hello,

Thank you for your contribution on this amazing tool.

When I used the AsBuiltReport.Veeam.VBR i reached 2 issues.

The first one, I had to used "Veeam.VBR" instead of "AsBuilt.Veeam.VBR" for -Report variable.
The Second one, I had "Invoke-AsBuiltReport.Veeam.VBR" not found.

I had to replace in AsBuiltReport.Veeam.VBR.psd1 :
FunctionsToExport = '*'
with
FunctionsToExport = @('Invoke-AsBuiltReport.Veeam.VBR')

Now the script generate the doc. The doc is empty so I guess there is a lot of work to do.
If I can help. Let me know.

**Comment by tpcarman** [comment]
Hi @salmeida77,

The Veeam As Built Report is in the very early stages of development and is not ready for testing yet. The `dev` branch is used for all code development. What is here now is simply the base framework for others to use to get started. When code is published to the `master` branch it is released to the PowerShell Gallery and becomes publicly available.

Some people have shown interest in contributing to this report so hopefully there will be something available in the not too distant future.

I welcome you to monitor this repository for updates by clicking the star button, or follow [@AsBuiltReport](https://twitter.com/AsBuiltReport) on Twitter for further updates to this and other report releases.

Thank you for your interest.
