### ISSUE TITLE
Change $HostBIOS to $HWBIOS in Get-AbrVbrBackupServerInfo.ps1

### ISSUE THREAD

**Issue by cevans3505** [AsBuiltReport/AsBuiltReport.Veeam.VBR#11]
**Describe the bug**
Looks like some refactoring was done and a few variables got missed.

**To Reproduce**
1. Get-AbrVbrBackupServerInfo.ps1
2. Lines 138 and 140
3. $HostBIOS.SerialNumber and $HostBIOS.Version output NULL as the $HostBIOS variable is never defined.

**Expected behavior**
Serial Number and Version to be displayed for Backup Server

**Screenshots**
![Snipaste_2022-02-01_04-22-31](https://user-images.githubusercontent.com/22597403/151942595-df3c1b41-fc7d-4422-a170-248049b5380d.png)

![Snipaste_2022-02-01_04-24-42](https://user-images.githubusercontent.com/22597403/151942897-2f505a6a-424b-4c9a-81d6-110815e385e1.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro for Workstations ver. 21H2 build 19044.1503
Browser: Chrome
Version: 97.0.4692.99

**Comment by rebelinux** [comment]
Thanks 😊
