### ISSUE TITLE
Typo in script

### ISSUE THREAD

**Issue by Emmer123** [AsBuiltReport/AsBuiltReport.Veeam.VBR#110]
### Bug description

/Src/Public/Invoke-AsBuiltReport.Veeam.VBR.ps1

line 56 mentions Get-AbrVbrServerConnections 

this should be Get-AbrVbrServerConnection without the s 

### Command-line input

New-AsBuiltReport -Report Veeam.VBR -Target localhost -Format Html,Word -OutputFolderPath 'E:\scripts' -Timestamp

### Steps to reproduce

just install the module on a fresh install and run an asbuiltreport

### Expected behaviour

a nice as built report :)

### Operating System

server 2022 standard 21h2

### PowerShell Version

Name                           Value                                                                                                                                                                         
----                           -----                                                                                                                                                                         
PSVersion                      5.1.20348.1366                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                       
BuildVersion                   10.0.20348.1366                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                           
SerializationVersion           1.1.0.1                

### PowerShell Modules

Name                    Version
----                    -------
AsBuiltReport.Core      1.3.0  
AsBuiltReport.Veeam.VBR 0.8.1  
PScribo                 0.10.0 

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Thanks!
