### ISSUE TITLE
Current logic incomplete for identifying Cloud Connect

### ISSUE THREAD

**Issue by carceneaux** [AsBuiltReport/AsBuiltReport.Veeam.VBR#121]
### Bug description

Cloud Connect is currently identified using this logic ([link](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/blob/dev/Src/Private/Get-AbrVbrCloudConnectTenant.ps1#L29)): 

`Get-VBRInstalledLicense | Where-Object {$_.CloudConnect -in @("Enterprise")}`

However, this logic does not work for service providers using Cloud Connect. Instead, the below logic should be used:

`Get-VBRInstalledLicense | Where-Object {$_.CloudConnect -ne "Disabled"}`

### Command-line input

New-AsBuiltReport -Report Veeam.VBR -Target $HostName -Credential $Credential -Format HTML -OutputFolderPath $Desktop -EnableHealthCheck -ReportConfigFilePath $ReportConfigFile -AsBuiltConfigFilePath $ConfigFile

### Steps to reproduce

1. Run script against Cloud Connect server using Veeam service provider license.
2. Check generated report
3. Report does not show detailed Cloud Connect information

### Expected behaviour

As long as correct InfoLevel is defined in `AsBuiltReport.Veeam.VBR.json`, Cloud Connect reports should work for both Enterprise and Service Providers.

### Screenshots

![CleanShot 2023-12-29 at 10 42 29](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/assets/17179966/67ef3c84-40ea-445f-823e-b48bdc92f841)

### Operating System

Server 2022

### PowerShell Version

![CleanShot 2023-12-29 at 10 43 05](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/assets/17179966/62c9b3d8-ffae-4040-ad35-7abf9299069c)

### PowerShell Modules

![CleanShot 2023-12-29 at 10 43 24](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/assets/17179966/fcedb8a5-93c6-478a-a1c1-c941e9f9c183)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Hello,

I no longer have access to a vcsp license, can you confirm that the report works in the 12.* Cloud Connect environment?

Regards,

**Comment by carceneaux** [comment]
My testing was performed in a 12.1 Cloud Connect environment and the report completed without error.
