### ISSUE TITLE
Consider remove support for Cloud Connect

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.Veeam.VBR#154]
### Veeam Backup & Replication version

12.1

### Description

Without the license and resources to run Cloud Connect there is a possibility that the CC section will be removed in a future release.

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this change request.

**Comment by carceneaux** [comment]
I'm happy to maintain this. 😄
