### ISSUE TITLE
[Bug]: Test v0.8.9 with Cloud Connect

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.Veeam.VBR#172]
### Veeam Backup & Replication version

12.2

### Bug description

Run the v0.8.9 of the report in a environment with Cloud Connect active and configured.

### Command-line input

New-AsBuiltReport

### Steps to reproduce

1. Update the report to v0.8.9
2. Run the report to make sure Cloud Connect section works

### Expected behaviour

Cloud Connect works in v0.8.9 of the report.

### Operating System

Windows

### PowerShell Version

v5.1

### PowerShell Modules

N/A

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).

**Comment by rebelinux** [comment]
Hey @carceneaux,

Can you help me with this request?

Regards,

**Comment by carceneaux** [comment]
Will do! 😊

**Comment by carceneaux** [comment]
Will do. Traveling this week but I’ll take care of it.
________________________________

**Comment by rebelinux** [comment]
I had a chance to run the report in a Cloud Connect environment and it worked fine. Closing this for now
