### ISSUE TITLE
[Bug]: Cannot find path to Veeam.Backup.PowerShell.dll because its on another driveletter

### ISSUE THREAD

**Issue by jstiops** [AsBuiltReport/AsBuiltReport.Veeam.VBR#179]
### Veeam Backup & Replication version

12.2

### Bug description

getting an error when running the new-asbuiltreport command. 
VERBOSE: [ 16:13:49:174 ] [ Document ] - Backup Copy Jobs InfoLevel set at 1.
Get-Item : Cannot find path 'C:\Program Files\Veeam\Backup and Replication\Console\Veeam.Backup.PowerShell.dll' because
 it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.Veeam.VBR\Src\Public\Invoke-AsBuiltReport.Veeam.VBR.ps1:443
 char:69
+ ... ge 1 -and ((Get-Item "C:\Program Files\Veeam\Backup and Replication\C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File....PowerShell.dll:String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

VERBOSE: [ 16:13:49:252 ] [ Document ] - Processing section 'Jobs Summary' completed.
Saved 'AsBuiltReport.Veeam.VBR.png' diagram to 'C:\Utils\AsBuiltReport-Veeam\'.

### Command-line input

New-AsBuiltReport -Report Veeam.VBR -Target veeamserverhostname -Format Text,Html,Word -OutputFolderPath 'C:\Utils\AsBuiltReport-Veeam\output' -ReportConfigFilePath 'C:\Utils\AsBuiltReport-Veeam\VeeamAsBuiltconfig.json' -Verbose -timestamp

### Steps to reproduce

i'm runnging all the latest versions of the modules required and the AsBultReport.Veeam.VBR module itself.
Running it against Veeam B&R 12.2.0.334 on windows server 2022, command locally started on the VBR server itself.
Does not seem to find Veeam.Backup.PowerShell.dll , probably because the software is not installed on the c-drive.

### Expected behaviour

no error

### Operating System

Windows Server 2022

### PowerShell Version

Name                           Value
----                           -----
PSVersion                      5.1.20348.2400
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2400
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PowerShell Modules

Name                    Version
----                    -------
AsBuiltReport.Core      1.4.0
AsBuiltReport.Veeam.VBR 0.8.10
PScribo                 0.10.0

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).

**Comment by rebelinux** [comment]
Can you show me the current install path?

**Comment by jstiops** [comment]
tried it with the new version, no error. thanks!
