### ISSUE TITLE
[Change Request]: correct module requirements

### ISSUE THREAD

**Issue by jstiops** [AsBuiltReport/AsBuiltReport.Veeam.VBR#180]
### Veeam Backup & Replication version

vNEXT

### Description

can you consider updating the module requirements?
I tried to do a offline installation of all modules currently listed as required, but list is missing PScribo and PSGraph.
Can't get it to run when those are not installed as well.

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this change request.

**Comment by rebelinux** [comment]
The request is to update the README or something else? I need more information!

**Comment by rebelinux** [comment]
Updated the modules requirements. Thanks!
