### ISSUE TITLE
[Change Request]: Repository capacity reporting in TB units

### ISSUE THREAD

**Issue by jstiops** [AsBuiltReport/AsBuiltReport.Veeam.VBR#181]
### Veeam Backup & Replication version

vNEXT

### Description

would like to request repository capacity numbers to be displayed in "TB" instead of "Gb" for easier reading in tables and diagrams.
"223521 Gb" is a waste of space.

nit-picking: "Gb" probably needs to be "GB"

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this change request.

**Comment by rebelinux** [comment]
can you show me an example?

Also did the infrastructure diagram get generated?

**Comment by rebelinux** [comment]
Please test version 0.8.11 and let me know!

**Comment by jstiops** [comment]
tried it, looks great! thanks!
