### ISSUE TITLE
'Invoke-AsBuiltReport.Veeam.VBR' is not recognized

### ISSUE THREAD

**Issue by kevkoala** [AsBuiltReport/AsBuiltReport.Veeam.VBR#2]
Having installed both the module as descibed, plus the core (which was not mentioned in your prep) to provide the basic functions, it failes to find the required module, script or function.

The "auto install" failed, so I cloned the github repo, and put in a subfolder called "0.1.0", as the "latest release" is also empty.

Config was carried out:

New-AsBuiltReportConfig -Report Veeam.VBR -FolderPath C:\reports -Filename k1

New-AsBuiltReport -Report Veeam.VBR -Target '(IP-Address-Removed)' -Username '(name-removed)' -Password '(removed)' -Format Html,Word -OutputFolderPath 'C:\reports' -Timestamp

It then produces this error:

----------------------------------------------
 <       As Built Report Configuration      >
----------------------------------------------
Would you like to save the As Built Report configuration file? (y/n): y
Enter a name for the As Built Report configuration file [AsBuiltReport]: AsBuiltReport.Veeam
Enter the path to save the As Built Report configuration file [c:\reports]:
Please wait while the Veeam VBR As Built Report is being generated.
New-AsBuiltReport : The term 'Invoke-AsBuiltReport.Veeam.VBR' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-AsBuiltReport -Report Veeam.VBR -Target '(IP-removed)' -Username ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

PS C:\reports>

**Comment by rebelinux** [comment]
Hello,

Sorry for the delay, it has been a busy week. As for the report, it is still in an early stage of development. I recently issued the first pull request and I am waiting for the project manager to analyze and approve it.

In the meantime you can use the following link as an example for preliminary testing.
https://technomyth.zenprsolutions.net/2021/12/22/homelab-veeam-vbr-documentation-with-asbuiltreport/

Thanks,
