### ISSUE TITLE
Module "AsBuiltReport.Veeam.VBR was not found at PowerShell Gallery

### ISSUE THREAD

**Issue by udotrautmann** [AsBuiltReport/AsBuiltReport.Veeam.VBR#4]
PS C:\Users\Administrator> Install-Module AsBuiltReport.Veeam.VBR
PackageManagement\Install-Package : Für die angegebenen Suchkriterien und den Paketnamen "AsBuiltReport.Veeam.VBR"
wurde keine Übereinstimmung gefunden. Verwenden Sie Get-PSRepository, um alle verfügbaren, registrierten Paketquellen
anzuzeigen.
In C:\Users\Administrator\Documents\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 Zeichen:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by udotrautmann** [comment]
PS C:\Users\Administrator> find-module -name AsBuiltReport.*

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.1.0      AsBuiltReport.Core                  PSGallery            A PowerShell module which provides the core fram...
1.3.1      AsBuiltReport.VMware.vSphere        PSGallery            A PowerShell module to generate an as built repo...
0.4.1      AsBuiltReport.VMware.NSXv           PSGallery            A PowerShell module to generate as built reports...
0.2.1      AsBuiltReport.Cisco.UcsManager      PSGallery            A PowerShell module to generate an as built repo...
0.4.1      AsBuiltReport.PureStorage.FlashA... PSGallery            A PowerShell module to generate an as built repo...
1.2.0.1    AsBuiltReport.Nutanix.PrismElement  PSGallery            A PowerShell module to generate an as built repo...
1.1.0      AsBuiltReport.VMware.ESXi           PSGallery            A PowerShell module to generate an as built repo...
1.0.1      AsBuiltReport.Rubrik.CDM            PSGallery            A PowerShell module to generate an as built repo...
0.6.1      AsBuiltReport.Microsoft.AD          PSGallery            A PowerShell module to generate an as built repo...
0.6.1      AsBuiltReport.NetApp.ONTAP          PSGallery            A PowerShell module to generate an as built repo...
0.3.0      AsBuiltReport.DellEMC.VxRail        PSGallery            A PowerShell module to generate an as built repo...
0.1.24     AsBuiltReport.Test.Module           PSGallery            A PowerShell module to generate an as built repo...
0.3.0      AsBuiltReport.VMware.SRM            PSGallery            A PowerShell module to generate an as built repo...

**Comment by pauLee** [comment]
It is still not official released in the PSGallery. You need to install it manually. You can follow the guide: https://technomyth.zenprsolutions.net/2021/12/22/homelab-veeam-vbr-documentation-with-asbuiltreport/
