### ISSUE TITLE
VMware Backup Proxies - table name

### ISSUE THREAD

**Issue by kevkoala** [AsBuiltReport/AsBuiltReport.Veeam.VBR#46]
**Describe the bug**
Table name shown under the table of VMware Backup Proxies is using the name of the last proxy in place of the VBR server name.

**To Reproduce**
Run a report, and examin the MS Word document, mine was table 18.

I know this is a minor issue, and easily fixed in the Word document afterwards.

Cheers,

Kev

**Comment by rebelinux** [comment]
Fix planned for v0.5.3 release. Thanks!
