### ISSUE TITLE
Include GFS Policy configuration

### ISSUE THREAD

**Issue by eduzimrs** [AsBuiltReport/AsBuiltReport.Veeam.VBR#49]
Hey Guys,

Is there any chances to include the Backup and Backup Copy Jobs GFS policies? that would be very helpful.
Thanks.

**Comment by rebelinux** [comment]
Does this format satisfy the needs of the request?

![image](https://user-images.githubusercontent.com/1002783/190261158-c8c0a1fb-05c7-45dd-86c2-662b2f7eb15a.png)

**Comment by rebelinux** [comment]
Yes, I will make sure to add this feature to any job that supports gfspolicy

**Comment by rebelinux** [comment]
The fix will be released in v0.5.4. Feel free to continue the bug hunting.

Thanks!
