### ISSUE TITLE
Application Aware Session showing wrong information

### ISSUE THREAD

**Issue by eduzimrs** [AsBuiltReport/AsBuiltReport.Veeam.VBR#50]
Hi,

I've found a possible bug in the report, we notice that in a particular job where we have a vCenter folder called "Infra" as source object, even disabling the AAIP it show as "Enabled = Yes" while it is Disabled for guest image processing.
I've attached the images where it shows what i'm trying to explain.

Thanks.

**Comment by eduzimrs** [comment]
![2022-09-14_13h48_47](https://user-images.githubusercontent.com/7524875/190215963-aeb865af-6251-4108-95c9-b9819c6b7c08.png)
![2022-09-14_13h46_52](https://user-images.githubusercontent.com/7524875/190215967-4ff0a820-64ed-472e-8929-717d322576fc.png)

**Comment by rebelinux** [comment]
Nice catch, the fix will be released in v0.5.4. Feel free to continue the bug hunting.

Thanks!
