### ISSUE TITLE
New-Chart Module Warning message

### ISSUE THREAD

**Issue by eduzimrs** [AsBuiltReport/AsBuiltReport.Veeam.VBR#69]
Hi,

I'm getting the following warning messages about the module New-Chart as per image attached.
Is it normal? or something is missing?
Thanks
![2022-10-04_14h58_01](https://user-images.githubusercontent.com/7524875/193892130-ad34777f-46b1-4f94-89b1-6cd66e1d8796.png)

**Comment by eduzimrs** [comment]
my bad

**Comment by rebelinux** [comment]
Need to install PScriboCharts module

install-module -name PScriboCharts

**Comment by rebelinux** [comment]
What version you are using?

**Comment by eduzimrs** [comment]
Was 0.5.4, it is embedded within 0.5.5 right? its all good.

**Comment by rebelinux** [comment]
Yes, it's my fault I forgot to include the module in version v0.5.4 😅 🙃
