### ISSUE TITLE
Capture VBR registry keys

### ISSUE THREAD

**Issue by carceneaux** [AsBuiltReport/AsBuiltReport.Veeam.VBR#83]
VBR registry keys can be found at the below location in the Windows registry. It's common for there to be custom/updated registry entries, especially in Cloud Connect environments. As such, it'd be nice to capture this information.

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Veeam\Veeam Backup and Replication`

My initial thought was to make this one of the more detailed levels like 3 in the report.

It should also exclude entries containing sensitive data like:

* ProviderCredentialsId
* SqlSecuredPassword

I'm currently working on adding this functionality and I'd welcome feedback. Thx in advance!

**Comment by rebelinux** [comment]
I believe the report retrieve that info if the healthchecks option is provided.

https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/commit/d9c6b3d92d6136b5304140c8bd95d9bbd5d64cbe

Maybe it's a better option to allow it to be displayed with level >=3 verbosity

**Comment by carceneaux** [comment]
Ooh... I like it! Thanks for pointing that out!

I agree that I think it makes more sense for it to be in detailed levels vs healthchecks.
